Use BaiWebCKi
SET IDENTITY_INSERT Product ON
Insert Product(Id, Name, Price, ImageURL, Descride) Values (1, N'Nike Blazer Low', N'2929000', N'https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a751495d-1cb9-4976-ab4f-9a2189464e8f/blazer-mid-77-next-nature-shoes-pDwZfH.png', N'The radiance lives on in the Nike Air Force 1, the basketball original that puts a fresh spin on what you know best: durably stitched overlays, clean finishes and the perfect amount of flash to make you shine.');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (2, N'Nike Blazer Mid', N'2149000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/bcf82e90-320d-4fde-b89b-44f84ae9d92a/blazer-mid-77-older-shoes-4Vk9Rd.png', N'Torn between 2 looks? Not any more—this AF-1 gets a 2-tone treatment from the tongue to the sole. The split-colour Swooshes and soles add just the right touch of interest, and mismatched branding on the tongue and backtab completes the look');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (3, N'Nike SB Zoom Mid', N'2779000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/85d7377e-5f14-472f-9d58-ce728ad8d85b/sb-zoom-blazer-mid-skate-shoe-cM9sg4.png', N'Torn between 2 looks? Not any more—this AF-1 gets a 2-tone treatment from the tongue to the sole. The split-colour Swooshes and soles add just the right touch of interest, and mismatched branding on the tongue and backtab completes the look');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (4, N'Nike Air Force 1', N'2299000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7f393827-5851-47a1-b581-c0543096617c/blazer-mid-77-older-shoes-4FSXkB.png', N'The split-colour Swooshes and soles add just the right touch of interest, and mismatched branding on the tongue and backtab completes the look. And don`t worry, it still delivers cushioned comfort and the classic AF-1 look with era-echoing 80s construction');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (5, N'Nike SB Zoom Blazer', N'2349000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2b01ba1c-d6da-47d7-9e3e-1261ae1fe1c0/air-force-1-07-lv8-shoes-pBxkmz.png', N'Torn between 2 looks? Not any more—this AF-1 gets a 2-tone treatment from the tongue to the sole. The split-colour Swooshes and soles add just the right touch of interest, and mismatched branding on the tongue and backtab completes the look');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (6, N'Nike Blazer Mid By You', N'3519000', N'https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/b1b3fd36-d06c-4ac6-ba51-3b85da09a0e9/custom-nike-blazer-mid-77-by-you.png', N'The radiance lives on in the Nike Air Force 1, the basketball original that puts a fresh spin on what you know best: durably stitched overlays, clean finishes and the perfect amount of flash to make you shine.');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (7, N'Nike Blazer Low Jumbo', N'2753000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/dcc9d0cc-7b96-4b0f-809d-8234489052fd/blazer-low-77-jumbo-shoes-xRGRJD.png', N'Shine in satin, stay classic in canvas or get luxe with leather. No matter what you choose, these AF-1s are all about you. 12 colour choices and an additional gum rubber option for the sole mean your design is destined to be one of a kind—just like you.');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (8, N'Nike Blazer Low Platform', N'2759000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f9caad72-8ba7-477c-a9be-59bd59b3744f/blazer-low-platform-shoes-1g6h57.png', N'Shine in satin, stay classic in canvas or get luxe with leather. No matter what you choose, these AF-1s are all about you. 12 colour choices and an additional gum rubber option for the sole mean your design is destined to be one of a kind—just like you.');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (9, N'Nike Air Peg Premium', N'3239000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0716b7f3-2969-4865-a852-d568008bfcf6/air-pegasus-89-shoes-Jh7lxZ.png', N'Let your design shine in satin, keep it classic in canvas and get luxe with leather. No matter what you choose, these AF-1s are all about you. 12 classic colour choices and an additional Gum option for the sole mean your shoe is destined to be one of a kind, just like you');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (10, N'Nike Air Max Plus III', N'5589000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/aqcdmfttkq4cuvv9nuwx/air-max-plus-iii-shoes-Qw64gh.png', N'The radiance lives on in the Nike Air Force 1, the basketball original that puts a fresh spin on what you know best: durably stitched overlays, clean finishes and the perfect amount of flash to make you shine.');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (11, N'Nike Revolution 6', N'1759000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7df57edf-bdc6-4320-a956-8ce37228cd1d/revolution-6-road-running-shoes-NC0P7k.png', N'Shine in satin, stay classic in canvas or get luxe with leather. No matter what you choose, these AF-1s are all about you. 12 colour choices and an additional gum rubber option for the sole mean your design is destined to be one of a kind—just like you.');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (12, N'Nike Elevate 3 Pro', N'2349000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8454b438-1a9d-4788-8750-00a57baf6da0/elevate-3-basketball-shoes-QT43Gj.png', N'Let your design shine in satin, keep it classic in canvas and get luxe with leather. No matter what you choose, these AF-1s are all about you. 12 classic colour choices and an additional Gum option for the sole mean your shoe is destined to be one of a kind, just like you');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (13, N'Nike Air Max Pulse Roam', N'2921000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/493f87d4-86f9-4fc5-8c63-ceff5b81a643/air-max-pulse-roam-shoes-NSfkP0.png',N'The Air Max Pulse Roam takes cues from its stylish forerunner and moves it in a more utilitarian direction. This means durability without the discomfort and style without the effort. Point-loaded Air cushioning—revamped from the incredibly plush Air Max 270—delivers the comfort youve come to trust.');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (14, N'Nike Air Max 97', N'2149000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/14de6943-8c87-4b9b-9585-80dea96a70d3/air-max-97-shoes-EBZrb8.png',N'Featuring the original ripple design inspired by Japanese bullet trains, the Nike Air Max 97 lets you push your style full-speed ahead.Taking the revolutionary full-length Nike Air unit that shook up the running world and adding fresh colours and crisp details, it lets you ride in first-class comfort.');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (15, N'Jordan One Take 4 PF', N'2779000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/54ff2b77-3635-4c89-99f5-963722644364/jordan-one-take-4-pf-shoes-v5trdl.png',N'Get that speed you need, just like Russ. Inspired by Russell Westbrooks latest signature shoe, the outsole of the Jordan One Take 4 wraps up nearly to the midsole so you can start, stop or change direction in an instant. Meanwhile, energy-returning Zoom Air cushioning in the forefoot keeps you going and going and going.');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (16, N'KD16 NRG EP', N'2299000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e0347482-728c-484d-82e0-137025aff890/kd16-nrg-ep-basketball-shoes-79MMfh.png',N'Kevin Durant is a true hooper. Hed be just as happy playing casual all afternoon as he would be dropping 40-pieces in the playoffs. When your avid appetite for the game cant be satisfied, lace up in the KD16s. Nike Air and Zoom Air work together to provide speed and stability for all four quarters, while the upper is lower and the overall load is lighter compared with the previous iteration. Its ideal for the hoopaholic who cant say no to just one more game. This special all-pink design honours KDs aunt who passed away from lung cancer in 2000, but inspires us all to continue to fight to find a cure. With its extra-durable rubber outsole, this version gives you traction for outdoor courts.');
Insert Product(Id, Name, Price, ImageURL, Descride) Values (17, N'Cosmic Unity 3', N'3519000', N'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c8f62751-6553-44d2-8883-6a093ba7709d/cosmic-unity-3-basketball-shoes-hcwmW0.png', N'Better for your game, designed with sustainability in mind—two things you care about—the Cosmic Unity 3 has a secure, lightweight design for a low-to-the-ground feel. It gives you cloud-like cushioning for explosive speed and quick changes of direction, the difference-makers in a game thats becoming more extraterrestrial.');
